### ISSUE TITLE
netlify deploy

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-8#11]
https://www.netlify.com/

**Comment by chauhannishith** [comment]
i don't have admin rights for this

**Comment by atherdon** [comment]
try it now. and don't forget that we can only push frontend on netlify.
for loopback server we'll need to create a heroku instance - which i can do myself or you can do it and master how heroku working

**Comment by atherdon** [comment]
admin granted

**Comment by atherdon** [comment]
@chauhannishith  if you move frontend on netlify - can you post a link here?

**Comment by chauhannishith** [comment]
https://clever-shannon-ae5d27.netlify.com/
might not be perfect as the links need to be set for proper routes and navigation bar is not displayed until you login

**Comment by chauhannishith** [comment]
I think I cannot deploy this repository. Have you kept any restrictions on Oauth or I have to create a new one without the old stuff?

**Comment by atherdon** [comment]
are you tryin to deploy whole `master` or only `frontend` branch?

**Comment by chauhannishith** [comment]
only the frontend branch

**Comment by chauhannishith** [comment]
https://groceristar.netlify.com/ modified the name so that it is easy to remember

**Comment by chauhannishith** [comment]
The links don not work on phone. Do you know what needs to be done to make it working?
