### ISSUE TITLE
for some cases nodemon crashed by registerServiceWorker.js

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-8#13]
```
[nodemon] starting `node server/server.js`
[nodemon] Internal watch failed: watch /home/art/Documents/C/kyiv/loopback-tutor-intern-8/client_src/src/registerServiceWorker.js ENOSPC
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! reservations@1.0.0 watch: `nodemon server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the reservations@1.0.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Btw raven not working for server side bugs

**Comment by atherdon** [comment]
but `npm run start` works pretty well

**Comment by chauhannishith** [comment]
i commented the raven part in the last commit to prevent frequent messages when saving the new component as it restarts automatically on saving will start it after a get a little working sample

and the server js file contains some code which i need to remove as i shifted that part to react so it is possile that error might clear out when i clean the code

**Comment by atherdon** [comment]
got it. not a prob. i'm testing the role thing now. will keep you posted

**Comment by atherdon** [comment]
i assume this error was related to my ubuntu config
