### ISSUE TITLE
setup a heroku server for both of us, with separated mongo source

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-8#16]
and then combine with netlify sutff

**Comment by chauhannishith** [comment]
You will have to create an app in Heroku and invite me as a team member to it as I don't have access to this repository

**Comment by chauhannishith** [comment]
You haven't attached this repository in heroku. I don't have access to this

**Comment by chauhannishith** [comment]
feels like dumb that i had typed that yesterday and had not pressed send

**Comment by atherdon** [comment]
i connect git. btw, i assume this will be easier - i'll share my heroku cred with you at slack

**Comment by chauhannishith** [comment]
I have encountered one error related to heroku
How do I set a host? If I set it as 0.0.0.0 then it runs on heroku but for the verification email it fetches the host from config file and the link in email has 0.0.0.0 which won't reach anywhere

**Comment by atherdon** [comment]
hmm, strange thing...


On 01-May-2018 at 01:48 PM, chauhannishith wrote:


I have encountered one error related to heroku
How do I set a host? If I set it as 0.0.0.0 then it runs on heroku but for
the verification email it fetches the host from config file and the link in
email has 0.0.0.0 which won't reach anywhere

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/loopback-tutor-intern-8/issues/16#issuecomment-385674614>,
or mute the thread

**Comment by atherdon** [comment]
maybe it's not the way to get a link for emails?
i mean we can store url at other place - maybe it's a better way?


On 01-May-2018 at 01:48 PM, chauhannishith wrote:


I have encountered one error related to heroku
How do I set a host? If I set it as 0.0.0.0 then it runs on heroku but for
the verification email it fetches the host from config file and the link in
email has 0.0.0.0 which won't reach anywhere

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/loopback-tutor-intern-8/issues/16#issuecomment-385674614>,
or mute the thread

**Comment by chauhannishith** [comment]
I dont know if there is a way to set up custom links or not but it fetches the host and port. I had setup a config file so that the host and port are set through process.env (which it is setting in case of port) . Also it is running on a localhost instance on heroku so that might be the problem. I copied the link and checked by replacing the host and port with site url and found that the rest of the link is correct

**Comment by atherdon** [comment]
Hmm, i should touch it myself. push the latest things to repo and i'll take a look. i just have break from groceristar homepage - so maybe can help
