### ISSUE TITLE
create a separated place, maybe another branch, where you'll have a react-app 

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-8#19]
that will be more configurable for moving into main groceristar project.
let's assume this situation: tomorrow we're moving that code into main project? can we doit? what we need to change.

>Yes, this same code will work with groceristar but will have to make some changes in the DB and links as in your project and also I am ready for anything you give me to do, front/back as it a bit rewarding to solve new challenges :)

Please find and specify each point, with links to code, so i'll know it too

**Comment by chauhannishith** [comment]
I have created a new branch named frontend and also mentioned in comments wherever I felt necessary about what needs to be done at that place and where the redirects are going

**Comment by atherdon** [comment]
good. but can you specify here a list of files(with line numbers). it will help us in future...

**Comment by atherdon** [comment]
is this done, right? so you can delete a client_src folder from master without worries?

**Comment by atherdon** [comment]
#29

**Comment by atherdon** [comment]
i want to close this task, but not sure if we build the project(link between front and server) in a proper way

**Comment by chauhannishith** [comment]
Even I am not sure if this is proper or not but once the entire project is complete we can shift the final build into the client folder(after correcting the links between them) and it will be able to run on heroku alone

**Comment by atherdon** [comment]
ok, i understand. i'm also start to feel that we're both ready to start to think about making a first steps, related to moving code that you did here into groceristar project

**Comment by atherdon** [comment]
closing this task
