### ISSUE TITLE
sentry/raven configuration

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-8#2]
`Raven.config('https://77aa2ee9a7ce484497f56278982a0809@sentry.io/305339').install()`

Init:
https://github.com/GroceriStar/groceristar/blob/master/server/server.js#L17

How to use this tracer:
https://github.com/GroceriStar/groceristar/blob/master/server/server.js#L60

if you'll cover your code well with this tracer - when you'll break something - I'll receive an email notification and will be able to understand more clearly what was goes wrong.

![image](https://user-images.githubusercontent.com/1469198/37542679-b443d8f0-2967-11e8-8d98-7fc3e9aabe6b.png)

**Comment by atherdon** [comment]
@chauhannishith did you setup this tool? can be helpful thing for us

**Comment by chauhannishith** [comment]
I thought that i have to set this up after you give a green signal to the code so i haven't done it yet

**Comment by atherdon** [comment]
@chauhannishith  did i add you to our Slack workroom? can i use your email that you shared with me? I think i can pause my articles and we can try to test your code right now

**Comment by chauhannishith** [comment]
No you haven't added me yet
Here's my email chauhannishith14@gmail.com

**Comment by atherdon** [comment]
invite was send

**Comment by atherdon** [comment]
i think we can close this task, right?

**Comment by chauhannishith** [comment]
does it send you a message for every error i make?

**Comment by atherdon** [comment]
try to break something and we'll see :)

**Comment by atherdon** [comment]
yes i got it

**Comment by atherdon** [comment]
closing
