### ISSUE TITLE
check about jest knowledge 

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-8#21]
@chauhannishith did you read that article:https://medium.com/groceristar/things-that-should-read-and-use-javascript-intern-at-groceristar-april-18-collection-bd6541e9ae28 ?

**Comment by atherdon** [comment]
Let's make this task active for now. I want to improve our workflow, so adding simple tests to our components I think this is a good idea to do. In that article i put Jest section for this task too.
Tell me what do you think @chauhannishith

**Comment by chauhannishith** [comment]
ok i will start with this
