### ISSUE TITLE
i think this is a bad line

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-8#22]
https://github.com/ChickenKyiv/loopback-tutor-intern-8/blob/5b185d25e92bf72fb702023fb7be351df4422f02/providers.json#L8

because we'll need to change it.
check this for a references: https://github.com/GroceriStar/groceristar/blob/master/providers.json

**Comment by atherdon** [comment]
other things that i find:
https://github.com/strongloop/loopback-example-passport/blob/master/providers.json.template
https://www.npmjs.com/package/passport-google-token-loopback
but not sure if it works, for sure

**Comment by chauhannishith** [comment]
Corrected this. Shouldn't break anything,

**Comment by atherdon** [comment]
did you know how attach commits to issues?

**Comment by chauhannishith** [comment]
closes #no ?

**Comment by atherdon** [comment]
yeah, use it in commit message.
