### ISSUE TITLE
bug#1 configure ulrs in order to send emails

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-8#32]
>>I have encountered one error related to heroku
How do I set a host? If I set it as 0.0.0.0 then it runs on heroku but for the verification email it fetches the host from config file and the link in email has 0.0.0.0 which won't reach anywhere

this was still unsolved, right? @chauhannishith 

>I dont know if there is a way to set up custom links or not but it fetches the host and port. I had setup a config file so that the host and port are set through process.env (which it is setting in case of port) . Also it is running on a localhost instance on heroku so that might be the problem. I copied the link and checked by replacing the host and port with site url and found that the rest of the link is correct

**Comment by atherdon** [comment]
#29

**Comment by chauhannishith** [comment]
yes, this is still pending
