### ISSUE TITLE
login from server homepage via google auth

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-8#47]
![page not found](https://user-images.githubusercontent.com/1469198/40280399-3bb18bc2-5c5b-11e8-908e-75e73f9f27f2.png)

**Comment by chauhannishith** [comment]
![image](https://user-images.githubusercontent.com/29725515/40292191-612e59f2-5ce7-11e8-9c27-b868d680a49e.png)
I tried and i can't see any error

**Comment by chauhannishith** [comment]
should i consider this as closed?

**Comment by atherdon** [comment]
you used a link from netlify. i used link from server homepage. i think in order to remove this confusing - i'll remove some code from loopback server.

**Comment by chauhannishith** [comment]
whichever link you use on successful completion you will be redirected to netlify because that is hard coded in providers.json

**Comment by chauhannishith** [comment]
I dont think we can replace json with js if it is coded to accept json as input but if it can accept then we can surely change it

**Comment by atherdon** [comment]
not replace, but sometimes use variables from .env
Ok, i think this is not a problem right now


On 30-May-2018 at 02:58 PM, chauhannishith wrote:


I dont think we can replace json with js if it is coded to accept json as
input but if it can accept then we can surely change it

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/loopback-tutor-intern-8/issues/47#issuecomment-393195065>,
or mute the thread
