### ISSUE TITLE
move logo

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-8#7]
https://github.com/GroceriStar/design/blob/master/LOGO1.png

**Comment by atherdon** [comment]
is this done? if yes, please close this issue

**Comment by chauhannishith** [comment]
I have only added this in browser icon, do you want me to place this anywhere else?

**Comment by atherdon** [comment]
display it in header too


On 04-May-2018 at 06:40 AM, chauhannishith wrote:


I have only added this in browser icon, do you want me to place this
anywhere else?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/loopback-tutor-intern-8/issues/7#issuecomment-386516886>,
or mute the thread
