### ISSUE TITLE
remove memory datasource from configs

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-8#9]

**Comment by chauhannishith** [comment]
Do you mean "db" in datasources.json?

**Comment by atherdon** [comment]
yeah

**Comment by atherdon** [comment]
i assume that i can broke a lot of things, but we need to move from file with data into all data at mongo. because right now it's hard to debug

**Comment by chauhannishith** [comment]
I haven't stored any data in memory  except the required session storage

**Comment by chauhannishith** [comment]
this also has been done
